# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
import numpy as np

x = np.arange(0,10)

x.reshape((1,2,5))

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [27]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.repeat(np.array((1)), 10).reshape(2,5)

np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [32]:
arr3 = np.arange(0,10).reshape(2,5)
arr4 = np.repeat(np.array(1), 10).reshape(2,5)

np.hstack((arr3, arr4))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [35]:
x = np.arange(0,10).reshape(2,5)
x.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [38]:
y = np.arange(0,15).reshape(3,5)
y.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [42]:
z = np.arange(0,15).reshape(5,3)

z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [45]:
arr5 = np.arange(0,25).reshape(5,5)

np.power(arr5, 2)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [50]:
arr6 = np.arange(0,30).reshape(5,6)

arr6.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [52]:
np.std(arr6)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [53]:
np.median(arr6)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [54]:
np.transpose(arr6)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [55]:
arr7 = np.arange(0,16).reshape(4,4)
np.trace(arr7)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [56]:
np.linalg.det(arr7)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [69]:
arr9 = np.arange(100).reshape(10,10)

print("5th Percentile: ", np.percentile(arr9, 5))
print("======================")
print("95th Percentile: ", np.percentile(arr9, 95))

5th Percentile:  4.95
95th Percentile:  94.05


## Question:15

### How to find if a given array has any null values?

In [80]:
arr10 = np.array([1,2,3,None,5])

is_null = lambda arr10: print("Array has null values") if None in arr10 else print("Array does not have any null values")

is_null(arr10)

Array has null values
