# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
w = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
w = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
w.shape

(39,)

5. Print the type of the previous array in question 3

In [6]:
w.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [10]:
np.__version__

np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/syedw/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/syedw/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/syedw/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

7. Print the dimension of the array in question 3


In [11]:
w.ndim

1

8. Create a boolean array with all the True values

In [12]:
np.ones(5, dtype=bool)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [14]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

10. Create a three dimensional array



In [16]:
b = np.zeros((5,5,2))
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [20]:
c = np.arange(10,49)

d = c[::-1]
print ("Below is the Reverse vector")
d

Below is the Reverse vector


array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [24]:
e = np.zeros((10))

e[4]=1
e

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [27]:
mat_three = np.identity(3)

print("3x3 identity matrix: ")
mat_three

3x3 identity matrix: 


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [30]:
arr = np.array([1, 2, 3, 4, 5])

conv_arr = arr.astype(np.float)

print("The Converted array type now: " + str(type(conv_arr[0])))

The Converted array type now: <class 'numpy.float64'>


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [31]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [32]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

comp_arr = arr1 > arr2

comp_arr

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [35]:
arr[arr % 2 == 1]

array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [45]:
np.put(arr, [0,1,2,3,4], [-1])
arr

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [47]:
arr = np.arange(10)
np.put(arr, [5,6,7,8], [12])
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [51]:
f = np.ones((10,10))

f[1:-1]=0
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [4]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

np.where(arr2d==5,12,arr2d)

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [5]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[arr3d<=3]=64

arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [38]:
x = np.arange(10).reshape(2,5)
x[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [39]:
x = np.arange(10).reshape(2,5)
x[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [47]:
x = np.arange(10).reshape(2,5)
x[::,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [55]:
y = np.random.randn(10,10)

y_min = y.min()
print("Minimum value of an array: ", y_min)

y_max = y.max()
print("Maximum value of an array: ", y_max)

Minimum value of an array:  -3.0246607605538856
Maximum value of an array:  2.081695077824963


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [56]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [59]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where( a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [73]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  

data = np.random.randint(7, size=random.randrange(1, 10))

print(data)

print(np.where(name[data] != "Will"))

[0 3 2 3 4]
(array([0, 1, 3], dtype=int64),)


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [74]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  

data = np.random.randint(7, size=random.randrange(1, 10))

print(data)

print(np.where((name[data] != "Joe") & (name[data] != "Will")))

[2 2 1 4 6 2]
(array([], dtype=int64),)


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [75]:
arr2d = np.random.uniform(low=1.0, high=15.0, size=(5,3))

arr2d

array([[13.75728134,  6.15984047,  9.0326104 ],
       [11.03965679, 12.25286613, 13.71343876],
       [ 1.3358232 ,  8.45020905,  9.92368948],
       [ 6.16383813,  1.56578541,  8.63956422],
       [ 4.35345193,  6.24018526, 12.96434389]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [76]:
arr2d = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))

arr2d

array([[[13.5785667 , 10.86504998, 11.77478003,  9.14097364],
        [10.80302369, 14.96951184,  4.41107322,  4.8481313 ]],

       [[14.0985096 ,  8.28967018, 10.11676558,  9.71234519],
        [15.34193393, 12.83222861, 14.52290834,  5.89462161]]])

33. Swap axes of the array you created in Question 32

In [78]:
np.swapaxes(arr2d, 0, 1)

array([[[13.5785667 , 10.86504998, 11.77478003,  9.14097364],
        [14.0985096 ,  8.28967018, 10.11676558,  9.71234519]],

       [[10.80302369, 14.96951184,  4.41107322,  4.8481313 ],
        [15.34193393, 12.83222861, 14.52290834,  5.89462161]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [82]:
import math

a = np.arange(10)

b = filter(lambda arr: arr if math.sqrt(arr) > 0.5 else 0, a)
np.asarray(list(b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [96]:
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
np.where(arr1 == arr2)

[5 0]
[8 3]


(array([], dtype=int64),)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [97]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [98]:
a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

com_items = np.intersect1d(a, b)

a = filter(lambda x: x if x not in com_items else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [101]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [100]:
matrix = np.random.randint(20, size=(random.randint(0, 5), random.randint(0, 5)))
np.cumsum(matrix)

array([11], dtype=int32)